# Generated by Django 2.2.5 on 2019-09-27 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserManagers',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('create_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_managers',
            },
        ),
        migrations.CreateModel(
            name='UserAuthorize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=20)),
                ('authorize', models.IntegerField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.UserManagers')),
            ],
            options={
                'db_table': 'user_authorize',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manage_lv', models.IntegerField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.UserManagers')),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
