# Generated by Django 2.2.5 on 2019-09-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanagers',
            name='password',
            field=models.CharField(max_length=64),
        ),
    ]
