# Generated by Django 2.2.5 on 2019-09-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190930_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageName',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'page_name',
            },
        ),
    ]
