# Generated by Django 2.2.5 on 2019-09-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_pagename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthorize',
            name='authorize',
            field=models.CharField(max_length=4),
        ),
    ]
